-- Create missing tables that are referenced in the hooks

-- Create players table (used by useRealtimeData.ts)
CREATE TABLE public.players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    contact_number numeric,
    mvp_medals integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Create gotd_players table (used by useGOTDRealtimeData.ts)
CREATE TABLE public.gotd_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    contact_number numeric,
    gotd integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Create games table (used by multiple hooks)
CREATE TABLE public.games (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    date date NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gotd_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Public Read Players" 
ON public.players 
FOR SELECT 
USING (true);

CREATE POLICY "Public Read GOTD Players" 
ON public.gotd_players 
FOR SELECT 
USING (true);

CREATE POLICY "Public Read Games" 
ON public.games 
FOR SELECT 
USING (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.players;
ALTER PUBLICATION supabase_realtime ADD TABLE public.gotd_players;
ALTER PUBLICATION supabase_realtime ADD TABLE public.games;

-- Set replica identity for realtime updates
ALTER TABLE public.players REPLICA IDENTITY FULL;
ALTER TABLE public.gotd_players REPLICA IDENTITY FULL;
ALTER TABLE public.games REPLICA IDENTITY FULL;