-- Create Koramangala players table
CREATE TABLE public.koramangala_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    contact_number numeric,
    mvp_medals integer DEFAULT 0,
    gotd integer DEFAULT 0,
    total_points integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Create Koramangala games table  
CREATE TABLE public.koramangala_games (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    date date NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.koramangala_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.koramangala_games ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Public Read Koramangala Players" 
ON public.koramangala_players 
FOR SELECT 
USING (true);

CREATE POLICY "Public Read Koramangala Games" 
ON public.koramangala_games 
FOR SELECT 
USING (true);

-- Enable realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.koramangala_players;
ALTER PUBLICATION supabase_realtime ADD TABLE public.koramangala_games;

-- Set replica identity for realtime updates
ALTER TABLE public.koramangala_players REPLICA IDENTITY FULL;
ALTER TABLE public.koramangala_games REPLICA IDENTITY FULL;