// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykrdwhbfmqvlmxdaspon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcmR3aGJmbXF2bG14ZGFzcG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODkzODcsImV4cCI6MjA3MDc2NTM4N30.Aj1sPboFz5cwM_dDCubBIwg3Fp71cDCsZGzKRGQ_mGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});